apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::618605584959:role/eksctl-eksctl-demo-nodegroup-ng-c-NodeInstanceRole-ZZHA2FN8EB0J
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-27T01:33:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1584"
  uid: 76189966-7860-46a6-8dd0-f2d24f73b908
